[pytest]
addopts = -p no:unraisableexception -p no:resourcewarning
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::ResourceWarning
    ignore::sqlalchemy.exc.LegacyAPIWarning