#!/usr/bin/env python3
"""Semantic-version release helper (dependency-free).

This is the dependency-free alternative to ``commitizen``: it touches only the
single version line in ``pyproject.toml`` and the hand-maintained
``CHANGES.rst`` (string ops, no parser dependency), and derives
``CHANGELOG.md`` from it. No new runtime dependency is introduced, so the main
``uv.lock`` is never regenerated by this tool.

Versioning model (matches the repo's existing convention):

* ``pyproject.toml``'s ``version = "X.Y.Z.dev"`` is the single source of truth.
  On release of ``X.Y.Z`` the tool sets it to the *next* dev (``X.Y.(Z+1).dev``
  by default).
* ``CHANGES.rst`` has a head block::

      Version X.Y.Z
      -------------
      Unreleased

      -   ...entries...

  Releasing renames ``Unreleased`` -> ``Released YYYY-MM-DD`` and prepends a
  new ``Version X.Y.(Z+1)`` / ``Unreleased`` block.
* ``CHANGELOG.md`` is a derived, never-hand-edited mirror regenerated from
  ``CHANGES.rst`` on every release (and on ``mirror``).

Change classification (``--level auto``) reads Conventional Commit subjects
since the last ``vX.Y.Z`` tag and maps: ``BREAKING CHANGE:`` / ``type!:``
-> major; ``feat:`` -> minor; ``fix:``/``perf:`` -> patch; anything else ->
patch. Classification only selects the *bump level*; humans still write the
prose in ``CHANGES.rst``.

Subcommands:

    bump   [--level {auto,major,minor,patch}] [--dry-run|--apply]
           [--github-output]
    notes  --version X.Y.Z           # extract a version's section as markdown
    mirror                          # regenerate CHANGELOG.md from CHANGES.rst

Usage::

    python scripts/changes.py bump --level patch --dry-run
    python scripts/changes.py bump --level auto --apply --github-output
    python scripts/changes.py notes --version 3.2.0
    python scripts/changes.py mirror
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PYPROJECT = ROOT / "pyproject.toml"
CHANGES_RST = ROOT / "CHANGES.rst"
CHANGELOG_MD = ROOT / "CHANGELOG.md"

VERSION_RE = re.compile(r'^version\s*=\s*"([^"]+)"', re.MULTILINE)
# ``Version 3.2.0`` + dash underline + a blank line + the status line. The
# repo's CHANGES.rst puts a blank line between the underline and the
# ``Unreleased``/``Released`` line, hence the ``\n\n``.
VERSION_HEADER_RE = re.compile(
    r"^(Version (\d+\.\d+\.\d+))\n(-+)\n\n(Unreleased|Released \d{4}-\d{2}-\d{2})\n",
    re.MULTILINE,
)
CONVENTIONAL_RE = re.compile(
    r"^(?P<type>\w+)(\((?P<scope>[^)]+)\))?(?P<bang>!)?:\s*(?P<subject>.*)$"
)
DEV_SUFFIX_RE = re.compile(r"\.dev\d*$")

CHANGELOG_HEADER = (
    "<!-- Auto-generated from CHANGES.rst by scripts/changes.py. Do not edit. -->\n"
    "# Changelog\n\n"
)


# --------------------------------------------------------------------------- #
# Version helpers
# --------------------------------------------------------------------------- #
def current_version() -> str:
    """Return the dev version string from ``pyproject.toml`` (e.g. '3.2.0.dev')."""
    text = PYPROJECT.read_text()
    match = VERSION_RE.search(text)
    if not match:
        raise SystemExit(f"could not find version= in {PYPROJECT}")
    return match.group(1)


def release_version(dev: str) -> str:
    """Strip a trailing ``.dev`` to get the version being released."""
    return DEV_SUFFIX_RE.sub("", dev)


def bump_version(released: str, level: str) -> str:
    """Return the next dev version after releasing ``released`` at ``level``.

    ``released`` is a clean ``X.Y.Z``; the result is ``X.Y.Z.dev`` of the
    *next* version per ``level``.
    """
    major, minor, patch = (int(p) for p in released.split("."))
    if level == "major":
        major, minor, patch = major + 1, 0, 0
    elif level == "minor":
        minor, patch = minor + 1, 0
    elif level == "patch":
        patch = patch + 1
    else:
        raise SystemExit(f"unknown level {level!r}")
    return f"{major}.{minor}.{patch}.dev"


def detect_level() -> str:
    """Classify conventional commits since the last ``vX.Y.Z`` tag."""
    last_tag = _last_release_tag()
    revrange = f"{last_tag}..HEAD" if last_tag else "HEAD"
    out = subprocess.run(
        ["git", "log", "--no-merges", "--format=%s%n%b", revrange],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    level = "patch"
    for line in out.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        if "BREAKING CHANGE" in line or "BREAKING-CHANGE" in line:
            return "major"
        m = CONVENTIONAL_RE.match(line)
        if not m:
            continue
        if m.group("bang"):
            return "major"
        if m.group("type") == "feat":
            level = "minor"
    return level


def _last_release_tag() -> str | None:
    out = subprocess.run(
        ["git", "tag", "--list", "v[0-9]*", "--sort=-v:refname"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    tags = [t for t in out.stdout.splitlines() if t]
    return tags[0] if tags else None


# --------------------------------------------------------------------------- #
# CHANGES.rst editing
# --------------------------------------------------------------------------- #
def rename_unreleased_to_released(changes_text: str, released: str) -> str:
    """Rename the head ``Unreleased`` line to ``Released YYYY-MM-DD``.

    Asserts the head block is for ``released`` to avoid bumping the wrong one.
    """
    m = VERSION_HEADER_RE.search(changes_text)
    if not m:
        raise SystemExit(
            "could not find a 'Version X.Y.Z / ---- / Unreleased' header block "
            "at the top of CHANGES.rst"
        )
    if m.group(2) != released:
        raise SystemExit(
            f"CHANGES.rst head version is {m.group(2)!r}, expected {released!r}; "
            "fix CHANGES.rst before releasing"
        )
    if m.group(4).startswith("Released"):
        # already released; idempotent no-op
        return changes_text
    today = date.today().isoformat()
    replacement = (
        f"{m.group(1)}\n{m.group(3)}\n\nReleased {today}\n"
    )
    return changes_text[: m.start()] + replacement + changes_text[m.end():]


def prepend_next_dev_block(changes_text: str, next_dev: str) -> str:
    """Prepend a fresh ``Version <release-of-next-dev> / Unreleased`` block.

    ``next_dev`` is e.g. ``3.2.1.dev``; the block header uses the clean
    ``3.2.1`` (the version that *will* be released next). The block is empty
    (no bullets); contributors add entries under it as usual.
    """
    next_release = DEV_SUFFIX_RE.sub("", next_dev)
    underline = "-" * len(f"Version {next_release}")
    block = f"Version {next_release}\n{underline}\n\nUnreleased\n\n"
    return block + changes_text


# --------------------------------------------------------------------------- #
# CHANGELOG.md mirror
# --------------------------------------------------------------------------- #
def rst_to_markdown_changes(changes_text: str) -> str:
    """Render CHANGES.rst as a Keep-a-Changelog-style markdown.

    Conservative conversion: ``Version X.Y.Z`` + its dash underline -> ``## X.Y.Z``;
    the ``Unreleased``/``Released <date>`` line is kept verbatim; ``-   `` bullets
    become ``- `` with continuation lines indented two spaces. Inline
    ``:pr:`/`:issue:`/`:ghsa:` roles are flattened to plain text. No reST
    dependency required -- this only needs to be readable, not round-trippable.
    """
    out = [CHANGELOG_HEADER]
    blocks = re.split(r"\n(?=Version \d+\.\d+\.\d+\n)", changes_text.strip())
    for block in blocks:
        block = block.strip()
        if not block:
            continue
        lines = block.splitlines()
        m = re.match(r"Version (\d+\.\d+\.\d+)", lines[0])
        if not m:
            continue
        out.append(f"## {m.group(1)}")
        idx = 1
        # skip the RST underline (a non-empty line of only dashes)
        if idx < len(lines) and lines[idx].strip() and set(lines[idx].strip()) <= {"-"}:
            idx += 1
        prev_was_bullet = False
        for line in lines[idx:]:
            stripped = _flatten_roles(line).strip()
            if stripped.startswith("-"):
                content = stripped[1:].strip()
                if content:  # a real bullet (the underline would have empty content)
                    out.append(f"- {content}")
                    prev_was_bullet = True
                    continue
            if stripped == "":
                out.append("")
                prev_was_bullet = False
            elif prev_was_bullet:
                out.append(f"  {stripped}")
            else:
                out.append(stripped)
                prev_was_bullet = False
        out.append("")
    return "\n".join(out).rstrip() + "\n"


_ROLE_RE = re.compile(r":(?:pr|issue|ghsa):`([^`]+)`")


def _flatten_roles(line: str) -> str:
    return _ROLE_RE.sub(r"\1", line)


# --------------------------------------------------------------------------- #
# pyproject.toml editing
# --------------------------------------------------------------------------- #
def set_pyproject_version(new_dev: str) -> str:
    text = PYPROJECT.read_text()
    new = VERSION_RE.sub(f'version = "{new_dev}"', text, count=1)
    PYPROJECT.write_text(new)
    return new_dev


# --------------------------------------------------------------------------- #
# Subcommands
# --------------------------------------------------------------------------- #
def _write_github_vars(*, version, new_version, next_dev_version, bump_level):
    """Append step-output / env-var lines for the release workflow.

    Writes ``version=<released>`` to ``$GITHUB_OUTPUT`` (job ``outputs``) and
    ``NEW_VERSION`` / ``NEXT_DEV_VERSION`` / ``BUMP_LEVEL`` to ``$GITHUB_ENV``
    (available to subsequent steps in the same job). Also echoes them so the
    plan log shows the resolved values. No-op outside GitHub Actions.
    """
    out_file = os.environ.get("GITHUB_OUTPUT")
    env_file = os.environ.get("GITHUB_ENV")
    out_lines = [f"version={version}"]
    env_lines = [
        f"NEW_VERSION={new_version}",
        f"NEXT_DEV_VERSION={next_dev_version}",
        f"BUMP_LEVEL={bump_level}",
    ]
    if out_file:
        with open(out_file, "a") as fh:
            fh.write("\n".join(out_lines) + "\n")
    if env_file:
        with open(env_file, "a") as fh:
            fh.write("\n".join(env_lines) + "\n")
    for line in out_lines + env_lines:
        print(line)


def cmd_bump(args: argparse.Namespace) -> int:
    dev = current_version()
    released = release_version(dev)
    level = args.level if args.level != "auto" else detect_level()
    next_dev = bump_version(released, level)

    changes_text = CHANGES_RST.read_text()
    new_changes = rename_unreleased_to_released(changes_text, released)
    new_changes = prepend_next_dev_block(new_changes, next_dev)
    new_changelog = rst_to_markdown_changes(new_changes)

    summary = (
        f"release plan:\n"
        f"  current dev version : {dev}\n"
        f"  releasing           : {released}  (level={level})\n"
        f"  next dev version    : {next_dev}\n"
        f"  CHANGES.rst         : Unreleased -> Released {date.today().isoformat()}, "
        f"prepend Version {DEV_SUFFIX_RE.sub('', next_dev)} block\n"
        f"  CHANGELOG.md        : regenerated ({len(new_changelog)} bytes)\n"
    )

    if args.github_output:
        # Surface the result to the release workflow: ``version`` becomes a
        # step output (job ``outputs.version``); ``NEW_VERSION`` etc. become
        # env vars for the subsequent commit/tag/push step.
        _write_github_vars(
            version=released,
            new_version=released,
            next_dev_version=next_dev,
            bump_level=level,
        )

    print(summary)

    if args.dry_run:
        print("--- CHANGES.rst diff (head) ---")
        _print_head_diff(changes_text, new_changes)
        print("--- CHANGELOG.md preview (head) ---")
        print("\n".join(new_changelog.splitlines()[:40]))
        return 0

    # --apply
    CHANGES_RST.write_text(new_changes)
    set_pyproject_version(next_dev)
    CHANGELOG_MD.write_text(new_changelog)
    print(f"applied: released {released}, set pyproject version -> {next_dev}")
    return 0


def cmd_notes(args: argparse.Namespace) -> int:
    changes_text = CHANGES_RST.read_text()
    md = rst_to_markdown_changes(changes_text)
    section = _extract_version_section(md, args.version)
    if section is None:
        print(f"no section for version {args.version} in CHANGES.rst", file=sys.stderr)
        return 1
    print(section)
    return 0


def cmd_mirror(_args: argparse.Namespace) -> int:
    changes_text = CHANGES_RST.read_text()
    CHANGELOG_MD.write_text(rst_to_markdown_changes(changes_text))
    print(f"regenerated {CHANGELOG_MD}")
    return 0


def _extract_version_section(md: str, version: str) -> str | None:
    # find "## <version>" and capture until the next "## "
    pattern = rf"^## {re.escape(version)}\n(.*?)(?=^## |\Z)"
    m = re.search(pattern, md, re.MULTILINE | re.DOTALL)
    return m.group(0) if m else None


def _print_head_diff(before: str, after: str) -> None:
    before_head = "\n".join(before.splitlines()[:8])
    after_head = "\n".join(after.splitlines()[:12])
    print("before:\n" + before_head)
    print("after:\n" + after_head)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_bump = sub.add_parser("bump", help="bump version + edit CHANGES.rst")
    levels = ["auto", "major", "minor", "patch"]
    p_bump.add_argument("--level", choices=levels, default="auto")
    group = p_bump.add_mutually_exclusive_group()
    group.add_argument("--dry-run", action="store_true", help="print plan only")
    group.add_argument("--apply", action="store_true", help="write in place")
    p_bump.add_argument(
        "--github-output", action="store_true", help="emit GITHUB_ENV vars"
    )
    p_bump.set_defaults(func=cmd_bump)

    p_notes = sub.add_parser("notes", help="extract a version's release notes")
    p_notes.add_argument("--version", required=True)
    p_notes.set_defaults(func=cmd_notes)

    p_mirror = sub.add_parser("mirror", help="regenerate CHANGELOG.md")
    p_mirror.set_defaults(func=cmd_mirror)

    args = parser.parse_args()
    if args.cmd == "bump" and not args.apply and not args.dry_run:
        # default to dry-run if neither flag given (safe)
        args.dry_run = True
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
